# Generated by Django 5.1.4 on 2024-12-28 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='講座名')),
                ('bunny_collection_id', models.CharField(max_length=64, verbose_name='bunny collection id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bunny_video_id', models.CharField(max_length=64, verbose_name='bunny video id')),
                ('title', models.CharField(max_length=256, verbose_name='動画タイトル')),
                ('description', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.course', verbose_name='講座')),
            ],
        ),
    ]
