# Generated by Django 5.1.4 on 2024-12-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='時間（分）'),
        ),
    ]
