# Generated by Django 5.1.4 on 2025-01-14 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='watch_progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='進捗'),
        ),
    ]
