# Generated by Django 5.1.4 on 2025-01-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_remove_video_watch_progress_videoprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='時間'),
        ),
    ]
